// File generated by FlutterFire CLI & Pulse Template.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        if (android.apiKey == 'YOUR_ANDROID_API_KEY') {
          // Fallback to web config to allow immediate database connection for release/debug testing
          return web;
        }
        return android;
      case TargetPlatform.iOS:
        if (ios.apiKey == 'YOUR_IOS_API_KEY') {
          // Fallback to web config to allow immediate database connection for release/debug testing
          return web;
        }
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj9vCsEwk45LwOuO6dDdWpS9JUc3dqEcY',
    appId: '1:881154618630:web:764430d2ca42c931269a87',
    messagingSenderId: '881154618630',
    projectId: 'message-23b1d',
    authDomain: 'message-23b1d.firebaseapp.com',
    storageBucket: 'message-23b1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn1cgqR6cr2IKsloAxL7Tle7aS1alhZcE',
    appId: '1:881154618630:android:f4bdf8e8f671fe47269a87',
    messagingSenderId: '881154618630', // Project default
    projectId: 'message-23b1d',
    storageBucket: 'message-23b1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_IOS_MESSAGING_SENDER_ID',
    projectId: 'message-23b1d',
    storageBucket: 'message-23b1d.firebasestorage.app',
    iosBundleId: 'io.pulse.app',
  );
}
